const NO_AUTHORIZATION = 'NO_AUTHORIZATION';
const PHONE_OR_PASSWORD_IS_INCORRECT = 'PHONE_OR_PASSWORD_IS_INCORRECT'
const AUTHORIZATION_EXPIRED_OR_INCORRECT = "AUTHORIZATION_EXPIRED_OR_INCORRECT"
const PHONE_ALREADY_EXISTS = "PHONE_ALREADY_EXISTS"
const CODE_IS_EXPIRED_OR_INCORRECT = "CODE_IS_EXPIRED_OR_INCORRECT"

module.exports = {
  NO_AUTHORIZATION,
  PHONE_OR_PASSWORD_IS_INCORRECT,
  AUTHORIZATION_EXPIRED_OR_INCORRECT,
  PHONE_ALREADY_EXISTS,
  CODE_IS_EXPIRED_OR_INCORRECT
}
