const ACTIVITY_START_TIME = "activityStartTime"
const ACTIVITY_END_TIME = "activityEndTime"
const ACTIVITY_START_TIME_FORMAT = "activityStartTimeFormat"
const ACTIVITY_END_TIME_FORMAT = "activityEndTimeFormat"

const CUSTOMER_BIRTHDAY = "customerBirthday"
const CUSTOMER_REGISTER_DAY = "customerRegisterDay"
const CUSTOMER_BIRTHDAY_FORMAT = "customerBirthdayFormat"
const CUSTOMER_REGISTER_DAY_FORMAT = "customerRegisterDayFormat"

module.exports = {
  ACTIVITY_START_TIME,
  ACTIVITY_END_TIME,
  ACTIVITY_START_TIME_FORMAT,
  ACTIVITY_END_TIME_FORMAT,

  CUSTOMER_BIRTHDAY,
  CUSTOMER_REGISTER_DAY,
  CUSTOMER_BIRTHDAY_FORMAT,
  CUSTOMER_REGISTER_DAY_FORMAT
}
